### ISSUE TITLE
Build for local development

### ISSUE THREAD

**Issue by geobra** [Karry/osmscout-sailfish#1]
While building for arm or i486 target works fine, building for local development does not work for me.

After installing the qt dependencies, I got this error after the cmake line from the Readme:
-----------------------------------
-- Requiered dependencies:
--  Qt5 found................................ YES
--  OpenMP compiler support found............ YES
--  SailfishApp library found................ NO
CMake Error at CMakeMod/MacroUtils.cmake:44 (message):
   SailfishApp library is needs. You need to install the SailfishApp library  development package.
Call Stack (most recent call first):
  CMakeLists.txt:89 (PRINT_LIBRARY_STATUS)

**Comment by Karry** [comment]
Hi. For local development, you need install `libsailfishapp` locally. You will found it here: https://github.com/sailfish-sdk/libsailfishapp

I will add this note to README.

**Comment by Karry** [comment]
Did it work now? If you have problems still, please reopen this issue.
