### ISSUE TITLE
Can't open routing service...

### ISSUE THREAD

**Issue by eson57** [Karry/osmscout-sailfish#107]
Routing still don't work for me. I get "Can't open routing service" whatever I try. Error message is also untranslated as you can see, and why do I have to wait 10 sec. before I DON'T get service?  ;-)

![screen_20180430_001](https://user-images.githubusercontent.com/2996154/39420194-c76c6d60-4c63-11e8-8dbb-f77d358559fa.png)

**Comment by atlochowski** [comment]
maybe you should try to reinstall app. For me everything is working ok.

**Comment by Karry** [comment]
You should update all your maps to database format 17. There was significant change in router graph disk format and I decided to drop backward compatibility in this case. It would be complicated. I will add note to changelog about that.

**Comment by eson57** [comment]
Ok, thanks. I didn't notice the database change.
