### ISSUE TITLE
RPM build errors

### ISSUE THREAD

**Issue by jialinxie** [Karry/osmscout-sailfish#112]
Hi,
 i want to run this demo on emulator.
when i build osmscout for sailfish according this Wiki.
[https://github.com/Karry/osmscout-sailfish/wiki/Howto-build-for-Sailfish-OS](url)

it turns out these error:
**+ cp /usr/lib/libgomp.so.1 /home/deploy/installroot/usr/share/harbour-osmscout/lib/
cp: cannot stat `/usr/lib/libgomp.so.1': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.G2aGkw (%install)**

It has same error on my mac OS X 10.13.3 and windows 10;

then i try to install openMP on OS X, but also failed.
`brew install clang-omp`,

also installed llvm refer following link, but no luck.
[https://stackoverflow.com/questions/38971394/brew-install-clang-omp-not-working](url)

here are files produced after `mb2 -t SailfishOS-i486 build`
[mersdk@SailfishSDK rpmbuilddir-i386]$ ls
CMakeCache.txt	MultiDBRouting_automoc.cpp   Routing_automoc.cpp	 cs.qm	       es.qm			     hu.qm		   nb.qm     privateinclude
CMakeFiles	PerformanceTest		     SearchPerfTest		 de.qm	       fr.qm			     install_manifest.txt  nl.qm     sv.qm
Makefile	PerformanceTest_automoc.cpp  SearchPerfTest_automoc.cpp  dependencies  harbour-osmscout		     libmarisa.a	   nl_BE.qm
MultiDBRouting	Routing			     cmake_install.cmake	 en.qm	       harbour-osmscout_automoc.cpp  moc_AppSettings.cpp   pl.qm

how to fix this error and build rpm packet?
Any reply will be grateful！

**Comment by Karry** [comment]
Sorry, this hack was not documented. libgomp library is not in mb2 mapping (mb2 is crosscompilation helper). You have tu run these commands in SDK:
```
. /etc/os-release
sudo cp /srv/mer/toolings/SailfishOS-${VERSION_ID}/opt/cross/armv7hl-meego-linux-gnueabi/lib/libgomp.so.1.0.0  /srv/mer/targets/SailfishOS-${VERSION_ID}-armv7hl/usr/lib/libgomp.so.1
sudo cp /srv/mer/toolings/SailfishOS-${VERSION_ID}/usr/lib/libgomp.so.1.0.0  /srv/mer/targets/SailfishOS-${VERSION_ID}-i486/usr/lib/libgomp.so.1
```
I also updated wiki.

Thanks for reporting it.

**Comment by jialinxie** [comment]
build successful, now i see rpm packet.
thank you very much!
