### ISSUE TITLE
Routing fails

### ISSUE THREAD

**Issue by dikonov** [Karry/osmscout-sailfish#115]
I was unable to route from my current location (100m from a major road in a big city) and a manually picked point at a crossroads in the same city. The error message was "Can't find route node near start coord 55.8... N 37.5..."  

OSM Scout server can route offline between these locations in modrana and whogo maps, so that must be a bug of the OSM Scout app itself.

**Comment by Karry** [comment]
OSM Scout server may use differect routing backend (valhalla). Please send me exact possition where route lookup fails. I will take a look on it.

**Comment by dikonov** [comment]
This is a screenshot with the coordinates.
![20180615121436](https://user-images.githubusercontent.com/4271322/41460589-ed27b298-7095-11e8-99e5-de6ae30d1687.jpg)

**Comment by Karry** [comment]
Do you have updated Russian maps in OSM Scout? I tried it right now with latest map and it works.

from 55°52'41.94"N 37°33'04.70"E
to 55°52'01.10"N 37°32'30.23"E

Note that OSM Scout cant share databases with OSM Scout server...

**Comment by Karry** [comment]
I am closing this issue. Please reopen it when problems still occurs with latest Russia database (map) and try to get application log - from console (ssh) after setting these environment variables:

```
export LANG=en_US.UTF-8                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                   
export QT_LOGGING_TO_CONSOLE=1                                                                                                                                                                                                                     
export QT_LOGGING_DEBUG=1                                                                                                                                                                                                                          
export QT_NO_JOURNALD_LOG=1                                                                                                                                                                                                                        
export QT_MESSAGE_PATTERN='[%{if-debug}D%{endif}%{if-info}I%{endif}%{if-warning}W%{endif}%{if-critical}C%{endif}%{if-fatal}F%{endif}] %{time h:mm:ss.zzz} %{threadid} %{function}:%{line} - %{message}'                                            
export OSMSCOUT_LOG=debug  
```
