### ISSUE TITLE
map server mirror

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#116]
I can't find your mail so I ask you here. Do you want to have mirror for maps?

**Comment by Karry** [comment]
My email address is in git log: `lukas.karas@centrum.cz` ;-) Well, some mirror would be useful for redundancy and providing better bandwidth to users. But setup some mirror has usual problem - limited time and I am not sure that it is necessary...  Do you think so? What is you experience with map downloading?

**Comment by atlochowski** [comment]
to be honest i've never had any problems with downloading maps. sometimes it just takes long bug maps are quite bit. I asked you because at my work we have many mirrors of Linux distributions and BSD, Libreoffice and much more. So if you would like we can make mirror of maps for your app. It depends on you.

**Comment by Karry** [comment]
Thank you for the offer. It is possible that I will ask you for such mirror in the future, when hosting on my Raspberry Pi will be insufficient or there will be other problems... I am appreciate it! But I don't want to invest time for testing and changing configuration now.

Request to everyone that is watching this repository - let me know when you will have some issue with map downloading!
