### ISSUE TITLE
Help with translation

### ISSUE THREAD

**Issue by popanz** [Karry/osmscout-sailfish#119]
Hi Lukáš,
I'm updating German translation at the moment. But I have one problem:
There are some strings wich contain the word "collection" unfortunately I don't know the context so it's a little bit hard to translate for me.
I have searched in the application, but didn't found, where "collection" is used. So i suppose, it's for an upcoming feature. Can you maybe try to explain in which context the word "collection" will be used?
Thanks
Uli

**Comment by Karry** [comment]
Hi. Thank you for translation! 

Yes, collections is the new feature that will be in next release. It is similar to "Collections" in Here maps or "routes and places" in mapy.cz. It is internal database of places (waypoints) and routes, I call directory in this database "collection". Collection can be exported to gpx file or imported from it. Only places can be created directly in application now, but in feature will be possible to support gps tracking and store route to some collection. And in far far future will be possible to synchronise collections with some cloud service :-)

![collections](https://user-images.githubusercontent.com/309458/44843035-9c50da00-ac47-11e8-91d3-e2929290d208.png)

**Comment by popanz** [comment]
Thanks for explanation. Finished translation.
Thanks for OSM Scout! Keep up your great work!
Of course I'll help in any way I can. Unfortunately coding isn't my cup of  
tea.



Am 30.08.2018, 11:36 Uhr, schrieb Lukáš Karas <notifications@github.com>:

> Hi. Thank you for translation!
>
> Yes, collections is the new feature that will be in next release. It is  
> similar to "Collections" in Here maps or "routes and places" in mapy.cz.  
> It is internal database of places (waypoints) and routes, I call  
> directory in this database "collection". Collection can be exported to  
> gpx file or imported from it. Only places can be created directly in  
> application now, but in feature will be possible to support gps tracking  
> and store route to some collection. And in far far future will be  
> possible to synchronise collections with some cloud service :-)
>
> ![collections](https://user-images.githubusercontent.com/309458/44843035-9c50da00-ac47-11e8-91d3-e2929290d208.png)
>
