### ISSUE TITLE
Maps for Mayotte and Martinique missing

### ISSUE THREAD

**Issue by dirteat** [Karry/osmscout-sailfish#123]
Hi there,
after the last update, I am updating French/* maps. But the system fails at downloading the updates for Mayotte and Martinique, even though they are in the list to be updated.

Thanks,
Cheers.

**Comment by Karry** [comment]
Hi. Tank you for report. I am using planet extracts provided by Geofabrik company to build maps. It seems that these islands are not included in [France region](http://download.geofabrik.de/europe/france.html) nor any region of [central america](http://download.geofabrik.de/central-america.html).

I will try to find a way how to provide it separately...

**Comment by Karry** [comment]
Btw, are you sure that it is issue for OSMScout, nor OSMScout-server ?

**Comment by Karry** [comment]
Anyway, I just import Mayotte (separate map in Africa) and Martinique as "Caribbean islands" in "Central America".  I am closing this issue. Feel free to reopen it when you will have some problems with these maps.

**Comment by dirteat** [comment]
Sorry, yes, it was an issue with osmscout server! But, you've fixed it, it works now!
Thanks a lot!
