### ISSUE TITLE
Update of a map fails due to 'directory already exists'

### ISSUE THREAD

**Issue by PawelSpoon** [Karry/osmscout-sailfish#150]
Hello Karry,
i did try to update a downloaded map today, the remorse time appears with the message that directory does already exist.
no matter if you just wait, or swipe it ways the update does not happen.

I am using you most recent version.

**Comment by Karry** [comment]
Hi. Is possible that some previous update was interrupted? Downloader dont support refreshing of partial download now :-( Only solution is to remove this directory manually from file manager and start update again...

**Comment by PawelSpoon** [comment]
can be, there were some 0 size files in the folder.
i have deleted the folder and now download is running.
so a known_limitation :-)

**Comment by Karry** [comment]
I made few changes in library to make sure that partially downloaded database is cleaned up after error... 

See comments in changelog:
```
- rewrite downloader internals, improve error handling
- harden map downloader: better error handling, fix "update all" action
```

Please re-open this issue if you will see this issue again with recent OSM Scout

**Comment by atlochowski** [comment]
@Karry It happened to me today, with the newest version (2.13).
After app update I checked if I have to download newer maps. I started downloading and they close an app.
After reopening app it was impossible to download newest maps. It showed me "directory already exists'"

**Comment by Karry** [comment]
You are right. When application is terminated, it suppose to delete partially downloaded database... I was working in the past, but right now, files are downloaded, but empty directory left there. OMG :-/

**Comment by Karry** [comment]
fix is ready and will be included in next release. see https://github.com/Framstag/libosmscout/pull/1081
