### ISSUE TITLE
featureRequest: revamping aboutPage 

### ISSUE THREAD

**Issue by GNUuser** [Karry/osmscout-sailfish#155]
like this the aboutPage, also deleting the strings "AboutPage"  of this page it is not more needed  : )
also with this FR will close issue #99 

                OSMScout
                    V: 2.0.0

a example here how look like the new desing by using PodQast-app as example , pureMaps- rinigus is already for it. so what you think karry on it? 
![podcast](https://user-images.githubusercontent.com/45316884/55761704-425e9100-5a2e-11e9-95fa-97becc236109.png)
![OSMscout](https://user-images.githubusercontent.com/45316884/55761705-425e9100-5a2e-11e9-8520-b0bd7979dee4.png)
![OSMSCot](https://user-images.githubusercontent.com/45316884/55761780-805bb500-5a2e-11e9-9357-487117fc8013.png)
![Uploading OSMSCot.png…]()

**Comment by GNUuser** [comment]
what you think?

**Comment by Karry** [comment]
Sorry for my late reply. Yes, using some graphics in about page header is a good idea. I am just focusing more to missing features than "graphical identity" of the application :-) Do you think that I should use same image (map background) as it is used on the Harbour page?

**Comment by GNUuser** [comment]
ok
 yes you can use same image from harbour.
@karry what is Scout from OSM Scout?

**Comment by Karry** [comment]
what do you think?

portrait:
![about-header1](https://user-images.githubusercontent.com/309458/57472993-20576900-728f-11e9-8d04-b4672b63e7b8.png)

landscape:
![about-header2](https://user-images.githubusercontent.com/309458/57472994-20efff80-728f-11e9-8298-38e1da3b15eb.png)

**Comment by Karry** [comment]
Thank you for this idea. It looks better now

**Comment by GNUuser** [comment]
looks pretty now. thank you.
i like the "limit" Style  a lot.
