### ISSUE TITLE
mapsDownloader

### ISSUE THREAD

**Issue by GNUuser** [Karry/osmscout-sailfish#162]
i having issues to updating or downloading maps, not sure if it is for new release or before.
thanks.

**Comment by Karry** [comment]
What is exact behavior? I had problem with downloading multiple times in the past, but was caused by network issues usually. I was not able to reproduce it on stable wifi and was not able to collect logs from these failures :-( It is reproducible for you?

**Comment by Karry** [comment]
I just analyse one of older coredump and it seems that file size that was stored in my SD card was larger than original file on the server! I will have to test re-establishing interrupted download...

**Comment by Karry** [comment]
Cleaning the internals... https://github.com/Framstag/libosmscout/pull/742

**Comment by GNUuser** [comment]
I fixed this by deleting the maps manually then download again in this way worked. 
So the bug is maybe deleting the maps in OSM Scout app , in this way the app can not delete the maps when is located , so when i try download this is getting conflict. something like this. :  )

**Comment by Karry** [comment]
Hi, 

I improved error handling in recent version (1.12) and eporting errors to UI... Moreover, when downloading fails for some reason, temporary, incomplete database is cleanup up... So whole process of downloading and upgrading database should be more resilient. 

Please let me know when you will found some issues in recent version. And Thank you for report ;-)

**Comment by GNUuser** [comment]
the thanks are for you.
