### ISSUE TITLE
There is missing files ! where can I find them please !

### ISSUE THREAD

**Issue by bhomaidan1990** [Karry/osmscout-sailfish#173]
src/MapStyleHelper.h
src/MapStyleHelper.CPP

**Comment by Karry** [comment]
Hi.

These files are referenced from old qmake project `osmscout-sailfish.pro`. It should be used anymore. Project should be configured by cmake... 

See  https://github.com/Karry/osmscout-sailfish/wiki/Local-development

and https://github.com/Karry/osmscout-sailfish/wiki/Howto-build-for-Sailfish-OS

**Comment by Karry** [comment]
I removed qmake project file from the project to avoid confustion.
