### ISSUE TITLE
Feature request: imperial distance units

### ISSUE THREAD

**Issue by threepistons** [Karry/osmscout-sailfish#174]
As a British user (also applies to Americans).
When I use the navigation feature.
I would like to be able to see the speed and speed limits in miles per hour and the distances in miles and yards.

**Comment by Karry** [comment]
Hi Helen. I was expecting that this request will come one day :-) I will add it to my todo list... What units should be used in peak elevation? Foots (ft.)? Peak elevation will be the most complicated, it require changes in the renderer, rest will be "just" UI...

**Comment by threepistons** [comment]
I've never used the elevation feature.  Mostly, I'm interested in having the distances and speed limits match the ones on road signage.

**Comment by Karry** [comment]
I just released version 1.14 with support of imperial units. Please let me know if there is still some lost label with metrics units or if some will need rework... For example using yards instead of feed.

**Comment by threepistons** [comment]
In the UK, the signs leading up to road junctions are in yards and most "finger signs" for pedestrians are in yards.

(Also, most drinks are sold in millilitres but beer is in (Imperial, not US) pints, food is weighed in kilograms but people are weighed in stones and pounds, and children are taught kilometers and meters at school but must learn miles and yards to drive.) :woman_shrugging: :confused:

**Comment by Karry** [comment]
Yeah, it is a mess. At least for someone who is not living there. I found out that US gallon is different from British one. Thankfully, there is no need for volume units in map application :-)

Anyway, lets clarify
 - speed limits and actual speed should be in miles per hour (mph)
 - distances during navigation in yards (yd) and miles (mil)
 - elevation in trip detail in feet (ft) ?
 - elevation above sea level in feet (ft a.s.l.) ?

**Comment by Karry** [comment]
closing this issue. feel free to reopen it if units are not correct somewhere

**Comment by clausmichele** [comment]
How to switch between metric and imperial? My system language is English but I need to use metric instead of imperial. Do you do automatically according to SO language?
