### ISSUE TITLE
Feature request: left-hand drive and clockwise roundabouts

### ISSUE THREAD

**Issue by threepistons** [Karry/osmscout-sailfish#175]
As a British user (also applies to Irish).
When I use the navigation feature.
I would like the roundabout icons and merge icons to be the correct way around for left-hand driving.

**Comment by Karry** [comment]
It is sad true, icons for route commands don't reflect real situation properly. Even in continental Europe are icons sometime wrong. Especially on highways...

**Comment by threepistons** [comment]
I have started work on flipping some of the icons.  Plan:
- Don't delete nor rename any existing icons, so as not to break existing code.
- Don't duplicate icons: where the driving side is irrelevant, there should only be one icon.
- Use a consistent change to the filename to differentiate left-hand drive icons from their right-hand drive counterparts: `enter-roundabout.svg` is the right-hand drive icon, `enter-roundabout-lhd.svg` is the left-hand drive counterpart.

**Comment by threepistons** [comment]
After considerable searching, flipping the icons is a simple matter of adding `transform="scale(-1, 1) translate(-20,0)"` in the right place in the SVG file.  Does the app support that SVG feature?

**Comment by Karry** [comment]
Thank you for the icons. It seems that Qt on SFOS support SVG transformations properly... I will try to implement code that detect roundabout direction...

**Comment by Karry** [comment]
Version 1.14 with roundabout clockwise direction was just released. Proper icons for highway crossing will require deeper testing and I want to do it together with navigation to lanes... Stay tuned.

**Comment by threepistons** [comment]
![Screenshot_20191130_001](https://user-images.githubusercontent.com/16269977/69921564-eba93a00-148a-11ea-9c6f-e6716c185648.png)

I'm afraid that the roundabout direction hasn't worked and now the exit is given as the wrong number.

**Comment by Karry** [comment]
It seems that there are two separate problems: 

 - roundabout direction is not propagated to the UI, it should be fixed by this commit: https://github.com/Karry/osmscout-sailfish/commit/3adfe0fc8aaf7a3739ba20705245bbff24ee0a31
 - computation of roundabout exit number. I have no idea where the problem may be. I would need to reproduce it locally. It is possible that it is issue with specific roundabout. Did you try to verify OpenStreetMap tags of this roundabout?

**Comment by threepistons** [comment]
I will go for a drive later this week and find more roundabouts to test.

In the previous version of OSM Scout, that routing was given as third exit.  It might be a UI issue?

**Comment by Karry** [comment]
Interesting. Code for exit number evaluation was not changed...?! I am not expecting that this is UI problem, but more likely route post-processing code... https://github.com/Framstag/libosmscout/blob/master/libosmscout/src/osmscout/routing/RoutePostprocessor.cpp#L680

**Comment by Karry** [comment]
Is there still issues? I believe that library should handle clockwise roundabouts properly.
