### ISSUE TITLE
When GPS is off or doesn't get fix accuracy is "-1" [Tracker]

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#190]
This "-1" can be a little bit confusing. 
In GPSInfo it's just "-" and in my opinion looks better, just no value.

**Comment by Karry** [comment]
Thank for report. It should be fixed by this commit: https://github.com/Karry/osmscout-sailfish/commit/fdc0dcd957dd9b33d268b6e0fd1cb43bd5b8b3f7

**Comment by atlochowski** [comment]
> Thank for report. It should be fixed by this commit: [fdc0dcd](https://github.com/Karry/osmscout-sailfish/commit/fdc0dcd957dd9b33d268b6e0fd1cb43bd5b8b3f7)

Yes but VerticalAccuracy is not changed

**Comment by atlochowski** [comment]
I think this should fix Vertical accuracy https://github.com/Karry/osmscout-sailfish/pull/191/commits/5d81e714d1fbc6889809d637b60ce1ffa2212bf1

**Comment by Karry** [comment]
Thanks, I cherry-picked your commit
