### ISSUE TITLE
It is not possible to export individual tracks

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#194]
It is possible to export whole collection but not individual tracks.
Please add a possibility to export individual tracks.

**Comment by Karry** [comment]
Hi. I am always think about collection as one gpx file, with multiple waypoints and tracks. So for me makes sence to export just whole collection at once...

Anyway, exporting single track would be easy to implement. Can you describe me your motivation?

**Comment by atlochowski** [comment]
Since MeeRun is dead and Luafhelden sport tracker crashes sometimes so I've started to use OSMScout to track my sport activities. So I need to make new collection for every sport activity or delete previous activity before export current one. 
If you want to export your activity to Strava etc you need every activity in seperate gpx file.

**Comment by Karry** [comment]
It will part of next release: https://github.com/Karry/osmscout-sailfish/commit/89411817f654ad4b1f124e5a24373be98ab7379d

**Comment by atlochowski** [comment]
Thank you!
