### ISSUE TITLE
It is not possible to display individual track on map just whole collection

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#195]
Please add a possibility to show just individual track on map.

**Comment by Karry** [comment]
Hi. I was thinking about that multiple times too. When I have multiple tracks in collection, they are overlapping and it is hard to see them. But displaying individual tracks has few difficulties: internal model is not ready for that, but it may ve updated with some effort. Second problem is UX. How to indicate that just few tracks from collection is displayed? How collection list should be changed, how collection detail (page with list of tracks)... Any suggestions?

**Comment by atlochowski** [comment]
I have some idea. I will write it today evening or tomorrow.

**Comment by atlochowski** [comment]
[https://www.dropbox.com/s/55c3ib14iln8yno/IMG_20200205_214632.jpg?dl=0](url)
Here you have a picture of my idea. It's not complete but look at it.
Firs I'm thinking about to remove Collections from main menu. Move it to Tracker.
In Tracker, you can see Collections and tracks not assigned to any Collection (you can assign this files to Collection from this menu). 
To show tracks on map you can use checkboxes or just long tap -> show on map -> when it showed on the map it can have some sign that means it showed on the map.
If this idea is ok for you I can work on more details of the next screens.
For example, I think before you can click "start tracking" there should be information that accuracy is high so you can start tracking.

**Comment by atlochowski** [comment]
I can't help you with code but if you are interested I can help with UI .

**Comment by sbridger** [comment]
Can you fudge this by moving or copying the track to a new collection? I noticed that I can move points from a gpx to another collection

**Comment by Karry** [comment]
it is one year already? :-) I started to implement missing parts today. this feature will be included in next release...

**Comment by Karry** [comment]
included in v2.20 release
