### ISSUE TITLE
Incorrect rendering seas

### ISSUE THREAD

**Issue by tomasz-c** [Karry/osmscout-sailfish#2]
On the maps offline you can not see the sea. This can be seen on the shore of Croatia, there is no distinction between land and sea.
For rivers and lakes rendering it is correct.
If necessary, I can attach screenshots.

**Comment by Karry** [comment]
Hi. Thanks for this issue. I know about this problem. In OSMScout for Sailfish are combined online tiles (in bottom layer, outside offline database bounding box) and tiles rendered offline (upper layer). Core library (libosmscout) supports sea/land rendering, but sea is rendered everywhere where is not land. When I switch on sea rendering, it overlap all online tiles...

So, for supporting sea/land correctly, I have to find a way howto crop seas by offline database (multi) polygon...

**Comment by Karry** [comment]
Hi. I invest some effort to solve this issue in recent release... Try it :-) And don't forget to update your maps! 

Please reopen this issue if you think that it is still valid and attach screenshot please...
