### ISSUE TITLE
Online maps are not sharp / future request for Hike and Bike style in ofline maps

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#206]
It's not new that online maps are blurred a little, and quite often pixels are visible.
It's not a big problem for me because I usually use OSM Scout in offline but sometimes I need hiking trails like on Hike and Bike style map. For now then only way is to use online maps in OSM Scout.

Is it possible to add a hike and bike style for offline maps? I think it's more useful than Borders style which is present in OSM Sout.

**Comment by Karry** [comment]
> online maps are blurred a little

Today's phones has high DPI (242 on Jolla One), but majority of online maps are rendered with 96 DPI. For that reason maps are upscaled (you may change that in map settings). Together with antialiasing it makes maps blurred... There is nothing that I can do about that. The only way is to find map provider that renders HiDPI raster maps...

> Is it possible to add a hike and bike style for offline maps?

I would love to. But essential for that is to have [route relations](https://wiki.openstreetmap.org/wiki/Relation:route) in [OSM Scout](https://github.com/Framstag/libosmscout) database somehow. But this kind of relation is not supported yet. To do it properly, it will takes few weeks. But it is high on my todo list.

**Comment by atlochowski** [comment]
Thank you for explanation about resolution.

I'm happy that route relations are high on your todo list.

**Comment by Karry** [comment]
Hike and bike routes will be added in upcoming release ;-)

![hike and bike routes](https://user-images.githubusercontent.com/309458/94120129-0f8da000-fe50-11ea-8cbb-d8dc8c91097e.png)

**Comment by atlochowski** [comment]
Nice :).
Thank you!
