### ISSUE TITLE
Moving/Revamp sentences 

### ISSUE THREAD

**Issue by GNUuser** [Karry/osmscout-sailfish#207]
Move the red square sentence to all the way down. | Screenshot edited with SF Imageworks app.

![Captura_20200318_001_edit](https://user-images.githubusercontent.com/45316884/76995313-11692a80-6926-11ea-977e-7bdc17b4c2fc.png)

**Comment by GNUuser** [comment]
Here I am not clear if the sentence "installed" will better that "available" because there is not option to download/install voices.

![Captura_20200318_002_edit](https://user-images.githubusercontent.com/45316884/76997419-a588c100-6929-11ea-991a-0ffbbe8bb424.png)

**Comment by Karry** [comment]
To first comment - I want to credit "VoiceOfMarble" project clearly and loudly. Why do you want to move it after list of voices?

To second comment, you can install voice just by tapping to check box on the left side... So, it is list of available languages, but also with possibility to download them and see what voices are available locally... True, "Installed voices" is not the best name for that button and page... Your suggestions?

![Snimek_20200318_001](https://user-images.githubusercontent.com/309458/77009986-359a2b00-6969-11ea-8660-86885be5960e.png)

**Comment by GNUuser** [comment]
I need to close this issue, we need to solve this,

**Comment by Karry** [comment]
Lets change the phrase to "Available voices"... https://github.com/Karry/osmscout-sailfish/commit/eb75ba1f72e8ebf4c7cee87005903a650d319277

**Comment by Karry** [comment]
To the first point, I want to keep VoiceOfMarble credits visible...
