### ISSUE TITLE
Wrong time in gpx files

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#216]
Maybe I'm wrong but I think there is a bug in gpx file generated by OSMScout.

For example <time>2020-05-04T10:09:57Z</time> means that this happened 10:09:57 Zulu time (UTC+0). So it's not local time. But OSMScout puts local time into gpx files. 

Tested on Jolla C

**Comment by Karry** [comment]
Damn. You are right!

**Comment by Karry** [comment]
It should be fixed by: https://github.com/Karry/osmscout-sailfish/commit/65df78def7b2a93a06b15969853bfb94399d1da9

Problem was that timestamp for track point was stored in local time, but loaded as UTC... So timestamp at exported gpx files is shifted even when timezone is UTC there...

**Comment by Karry** [comment]
Thank you for report!

**Comment by atlochowski** [comment]
> Thank you for report!

Thanks for fix and great app!

**Comment by atlochowski** [comment]
just check, and it's ok now. 
fix for Jolla 1 is ok as well.

**Comment by Karry** [comment]
Great!
