### ISSUE TITLE
Please change order of tracks in collections 

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#218]
Please change order of tracks in collections.
For now order is from the oldest to the latest but if you have lot of tracks order from the latest to the oldest is better. Usually, you want to see or export the latest tracks, not the oldest.

**Comment by Karry** [comment]
It makes sense, but I want to have it configurable. C++ part in collection model is ready. Now it is necessary implement UI part and setting persistency...

**Comment by Karry** [comment]
configurable ordering is available in new version 2.3. closing this issue
