### ISSUE TITLE
Small change in new strings

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#228]
I think it will be better if you change string "Date" to "Date, ascent" and this same for "Name" string. 

```
    <message>
        <source>Date</source>
        <translation>Data</translation>
    </message>
    <message>
        <source>Date, descent</source>
        <translation>Data, malejąco</translation>
    </message>
    <message>
        <source>Name</source>
        <translation>Nazwa</translation>
    </message>
    <message>
        <source>Name, descent</source>
        <translation>Nazwa, malejąco</translation>
    </message>
```

**Comment by Karry** [comment]
I don't think that it is necessary, because when you sorting strings, it is going ascent (a,b,c,d...) implicitly.

**Comment by atlochowski** [comment]
Yes, but it will look better than now. But it just my opinion.
My first impresion was, it is something wrong with adjustment.

**Comment by Karry** [comment]
I just reconsider it. Lets change it from next (2.5) release... https://github.com/Karry/osmscout-sailfish/commit/717ee624355d8971d04250b9fdb35feb80a895ce
