### ISSUE TITLE
The app shows a white screen without any menu/map

### ISSUE THREAD

**Issue by n3w** [Karry/osmscout-sailfish#230]
When I start the app, I get a white Screen and nothing else, it used to work, but stopped at some point. How can I troube shoot the issue?
Thanks for any help!

**Comment by Karry** [comment]
Hi. Which Sailfish OS version and OSM Scout version are you using on your device? Can you start it from the terminal with arguments "--log debug", redirect output to the file and post it here please?

Thanks. It sounds weird...

**Comment by n3w** [comment]
I'm abroad right now, thanks for the answer, I will try `--log debug` asap and report back!

**Comment by n3w** [comment]
I have latest OSM Scout version from Jolla store (2.1.0) and a somewhat old SF version: 3.0.3.9
Debug is attached:
[osmscout.log](https://github.com/Karry/osmscout-sailfish/files/4977282/osmscout.log)

A Screenshot of what I see:
![Screenshot_20200726_001](https://user-images.githubusercontent.com/5166607/88474449-ccce4b00-cf26-11ea-95ff-45260c334947.png)

**Comment by Karry** [comment]
Well, from the application log, I have no idea what may be wrong :-( It will be some Qt bug I guess. You may enable Qt debug messages by editing its configuration file `/home/nemo/.config/QtProject/qtlogging.ini` (if file or directory doesn't exists, just create it) and put this content there:
```
[Rules]
*.debug=true
qt.*.debug=false
```
Then try to run OSM Scout again...

Anyway, why you are not using latest SFOS version? If it is Qt bug, it may be solved in recent release...

**Comment by n3w** [comment]
ok, I finally managed to upgrade my SFOS to the latest (3.3.0.16) now OSM Scout works again.
Thanks for your assistance and your great app!!
