### ISSUE TITLE
Opinion about editing

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#244]
I really like that it's possible to edit track but...
When you want to crop, split etc track, it loads map then reloads to show whole track. If it's possible it would look better if you load whole track view without reloading.

**Comment by Karry** [comment]
You are right, it would be better behavior. Fixed by https://github.com/Karry/osmscout-sailfish/commit/53dfd058d1778104552392fee9359f0bf7aaeabf
