### ISSUE TITLE
Possiblitity to backup with My backup app

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#245]
It's nice backup app created by slava. It should be easy to implement this to OSM Scout.

https://openrepos.net/content/slava/my-backup

**Comment by atlochowski** [comment]
#246 done in this PR

**Comment by Karry** [comment]
Nice idea. It is pity that this functionality is not provided by SFOS itself.

Thanks for the merge request, I will take a look on it later this week.

**Comment by Karry** [comment]
I just looking to MyBackup screenshots and it is integrated with SFOS system backup! I will need to look source code, I am curious how it is working under the hood. Thank you @monich :-)

**Comment by Karry** [comment]
Nice, it is working (don't try restore)... 
![Screenshot_20210113_102120](https://user-images.githubusercontent.com/309458/104432312-2edc4480-5589-11eb-80d6-7a5b946a0f9f.png)

**Comment by atlochowski** [comment]
I know it's working, I made a backup to try, before MR.

**Comment by Karry** [comment]
released in v2.10
