### ISSUE TITLE
Offline maps download error

### ISSUE THREAD

**Issue by fedetft** [Karry/osmscout-sailfish#248]
Hi, first of all thanks for this great app.
Updated it today, and now in the Offline Maps menu I get this error:

Error transferring https://osmscout.karry.cz/latest.php?fromVersion=21&toVersion=22&locale=en

and can't update or download new maps.

**Comment by Karry** [comment]
Hi. Sorry for troubles. I was just upgrading packages on my server and my scripts stops working with recent php. It should be fixed now.

**Comment by fedetft** [comment]
Wow, that's a fast fix indeed!
