### ISSUE TITLE
street name trouble

### ISSUE THREAD

**Issue by Caballlero** [Karry/osmscout-sailfish#25]
-Problem to display street names as well in the new version v=0.17 - sf=2.0.5.6 
-The names of the streets are very small unable to read,even doing zoom.

**Comment by Karry** [comment]
Hi Carlos. What device are you using? Can you start `harbour-osmscout` from terminal and past first few lines from log start here? I want to know what DPI reports Qt on your device. On Jolla, it is:
```
[D] DBThread::DBThread:122 - Reported screen DPI:  242.236 
[D] DBThread::DBThread:124 - Map DPI override:  219 
```

Label size is defined in millimeters in stylesheet, real label size in pixel is computed from stylesheet size and device DPI.

Anyway, you hale option to override this value still - just open app menu, select "Map settings". There is slider "Map magnification"...

**Comment by Caballlero** [comment]
Yes, it is was fixed with  "Map magnification" everything  ok.   > close this <

 You are making a great app  :+1:   Routing is the most as expected

**Comment by Karry** [comment]
Great! But, can you look to the "Reported screen DPI" please? I just wan to be sure that there is nothing wrong in app.

**Comment by Caballlero** [comment]
Yes: [nemo@Sailfish ~]$ harbour-osmscout
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 -
Using Wayland-EGL
[D] main:74 - Usage of memory mapped files is supported.
[D] main:119 - Found storage: "/media/sdcard/5361-1C16"
[D] DBThread::DBThread:122 - Reported screen DPI:  293.934
[D] DBThread::DBThread:124 - Map DPI override:  250
TiledDBThread::TiledDBThread()     JOLLA C
