### ISSUE TITLE
Please add the german "Bundesländer" to the online map repository

### ISSUE THREAD

**Issue by Framstag** [Karry/osmscout-sailfish#251]
Germany is rather huge, it would be nice to have the german "Bundesländer" available too, if possible.

See https://download.geofabrik.de/europe/germany.html

**Comment by Karry** [comment]
Why not :-) https://github.com/Karry/osmscout-scripts/commit/629cbc5d3874ce5b85f1f7ec8dc8f2170e9d0c94
