### ISSUE TITLE
show/hide Collection/Overlays button on map 

### ISSUE THREAD

**Issue by sbridger** [Karry/osmscout-sailfish#255]
I am using with an overlay of POI from a GPX file - 5225 points. They can hide much of the map.

I would like a simple/fast/direct toggle button on the map screen to show/hide the currently selected collections/POI/overlays

**Comment by Karry** [comment]
Hi. This should be doable relatively easily. Do you have an idea what icon to use for such toggle? Because "star" is used for adding new waypoint already...

**Comment by sbridger** [comment]
Following your theme, you could have "star" inside the grey zone which has altitude/precision. Touching it would toggle the star.
It only shows over the map when there are selected collections/POI to show/hide.

---

BTW, as I was playing, I tried to touch the menu button, and slide it downwards to drag open a pulldown menu.  Might be thought for an intuitive sailfish-ish approach to opening the menu, since it seemed to happen automatically for me.

**Comment by sbridger** [comment]
OK, after using it a bit more, I see where the star-in-circle is used on the map.

Perhaps the icon symbol could be a double overlapping star. Again in a square button at the top, then its very different from the single star in a round button at the bottom.

**Comment by sbridger** [comment]
Thanks, I am looking forward to it!
I would probably locate it at the top left, so its not right next to the menu button. (and inadvertent clicks)

**Comment by sbridger** [comment]
Used it now. It really makes it easier for my use. thx.
