### ISSUE TITLE
OSMScout interferes with audio player

### ISSUE THREAD

**Issue by zipotron** [Karry/osmscout-sailfish#258]
Hello, I post in openrepos forum time ago that OSMScout stop audio player even when there is not voices installed. An it was fixed, now is not stopping the music any more, but, while navigation, in every intersection, you can notice a small cut of the sound, is like OSMScout wants to speak but don't do, is a bit annoying. I think that OSMScout pause the music and after that realize that there is not voice and then restart the music.
It is possible to deactivate the call in code that is playing the voices when there is not voice to play? this would fix the problem.
Thanks!

**Comment by zipotron** [comment]
@Karry I can try to fix it next week, and do a MR, if you are OK with that

**Comment by Karry** [comment]
Hi. 

Sorry, I didn't notice this bug. I am not playing music from phone when driving :-) And I have voice enabled. Problem will be probably in the fact that player playlist is setup even when no voice is configured. On this line: https://github.com/Framstag/libosmscout/blob/master/libosmscout-client-qt/src/osmscout/NavigationModule.cpp#L63

Btw, I recently (version 2.13) added `--simulate-position` command line option that starts simulating position by "replaying" GPX file. With this option it is possible to test navigation from working desk :-)

> I can try to fix it next week, and do a MR, if you are OK with that

I would appreciate it :-)

**Comment by zipotron** [comment]
@Karry OK! I will try it! Just a question, because the MR seams affect to the "libosmscout" Shall I do the MR directly to the "Framstag" repo, or to your fork?

**Comment by zipotron** [comment]
@Karry I will try to fix!

**Comment by Karry** [comment]
Please prepare MR to "upstream" - Framstag's repository. OSM Scout should be buildable with upstream library. My fork contains just extra patches for backward compatibility with older database formats.

**Comment by zipotron** [comment]
As soon as I have something I will, I apologize because I couldn't even start, I had a really busy week at work. But I will as soon I can!

**Comment by Karry** [comment]
No problem, I understand it. It is hobby :-)

**Comment by zipotron** [comment]
Hi Karry! At last I got time to do this! Yes, is true, initializes even if there is not voices, I guess I fixed, well, you did the 99%, I am testing now, I will close the issue because anyway I have to do the MR in Framstag's repository. I will push it today! Thanks!

**Comment by zipotron** [comment]
Hi Karry, sorry for close and now reopen the issue, I saw the solution, and correct the code, and actually when I tested in real life, in my car, just realized that I did bad job... I modified in libosmscout dependency the "navigationModule" constructor like this:
´´´
diff --git a/libosmscout-client-qt/src/osmscout/NavigationModule.cpp b/libosmscout-client-qt/src/osmscout/NavigationModule.cpp
index d5ac07adc..37657c656 100644
--- a/libosmscout-client-qt/src/osmscout/NavigationModule.cpp
+++ b/libosmscout-client-qt/src/osmscout/NavigationModule.cpp
@@ -36,6 +36,9 @@ NavigationModule::NavigationModule(QThread *thread,
   connect(settings.get(), &Settings::VoiceLookupDirectoryChanged, this, &NavigationModule::onVoiceChanged);
   connect(settings.get(), &Settings::VoiceDirChanged, this, &NavigationModule::onVoiceChanged);
   onVoiceChanged(settings->GetVoiceDir());
+  if (!QDir(voiceDir).exists()){
+    voiceDir.clear(); // disable voice
+  }
 }
´´´
Expecting that the error is that it initializes the mediaplayer even if there is no voice directory (that is my case). I was sure that was solved but no... Then I check if the voice directory is the same as the maps, and get it as not empty... But no, is a dedicated directory, and if there is no voices even didn't exists... Maybe check if in settings is set "no voice" and then invalidate initialization in the constructor? But if its this... I need a lot of time for study how works bridge from QML to code in Sailfish... I need support for that (and I have hard period at work!!!). Please, looking forward to your opinion, and hope to be able to help!

**Comment by zipotron** [comment]
Hi Karry, sorry for close and now reopen the issue, I saw the solution, and correct the code, and actually when I tested in real life, in my car, just realized that I did bad job... I modified in libosmscout dependency the "navigationModule" constructor like this:
`diff --git a/libosmscout-client-qt/src/osmscout/NavigationModule.cpp b/libosmscout-client-qt/src/osmscout/NavigationModule.cpp
index d5ac07adc..37657c656 100644
--- a/libosmscout-client-qt/src/osmscout/NavigationModule.cpp
+++ b/libosmscout-client-qt/src/osmscout/NavigationModule.cpp
@@ -36,6 +36,9 @@ NavigationModule::NavigationModule(QThread *thread,
connect(settings.get(), &Settings::VoiceLookupDirectoryChanged, this, &NavigationModule::onVoiceChanged);
connect(settings.get(), &Settings::VoiceDirChanged, this, &NavigationModule::onVoiceChanged);
onVoiceChanged(settings->GetVoiceDir());

    if (!QDir(voiceDir).exists()){
    voiceDir.clear(); // disable voice
    }
    }`
Expecting that the error is that it initializes the mediaplayer even if there is no voice directory (that is my case). I was sure that was solved but no... Then I check if the voice directory is the same as the maps, and get it as not empty... But no, is a dedicated directory, and if there is no voices even didn't exists... Maybe check if in settings is set "no voice" and then invalidate initialization in the constructor? But if its this... I need a lot of time for study how works bridge from QML to code in Sailfish... I need support for that (and I have hard period at work!!!). Please, looking forward to your opinion, and hope to be able to help!

**Comment by Karry** [comment]
Hi. Thank you for your investigation, even when you were not successful. I was able to reproduce this bug locally with position simulator. Root of the problem was hidden somewhere else. Take a look to https://github.com/Framstag/libosmscout/pull/1097 for more details.

**Comment by zipotron** [comment]
Was a pleasure to try! Thanks for the support!
