### ISSUE TITLE
Consider submitting to Chum

### ISSUE THREAD

**Issue by rinigus** [Karry/osmscout-sailfish#288]
As you have OSM Scout published in OpenRepos with extras not allowed at Harbour, maybe you could consider publishing it at Chum as well. I can see that you have already OBS builds which means that submitting to Chum is very easy. Ideally, Metadata should be added to RPM SPEC %description (or YAML if you use that under `description:`), screenshots are probably best served from github directly (using RAW URL). You could use Pure Maps record as a template since we share the same categories :) (see at https://github.com/rinigus/pure-maps/blob/master/rpm/harbour-pure-maps.spec#L77).

**Comment by Karry** [comment]
Hi Rinigus. It really looks simple. I never find the time to finish it. OBS user experience disappointed me a bit, as build definitions cannot be declarative, like Github actions... Anyway, may I ask you for review please? https://github.com/Karry/osmscout-sailfish/pull/290 Distribution via Chum may be handy.

**Comment by rinigus** [comment]
Sure, will do right away and look into your changes

**Comment by rinigus** [comment]
I don't know much about declarative actions, so probably didn't miss them then :) . OBS shines when you have many libs that you depend on. So, instead of submodules, you could have built and packaged libosmscout separately and used that as build dependency. Marisa is already available in Chum as I am using it already.

Also, I hope that all older SFOS versions would get your maps app right away as well. But there are some limitations with OBS, I agree

**Comment by rinigus** [comment]
Thank you very much for submitting it! It is now in main repository as well. To be sure that my OBS message did get to you and was not filtered as a spam:

I have added revision tag into your _service as we need it for reproducible builds. As soon as builds are ready, we will push package into sailfishos:chum. Corresponding change is in line 6 at https://build.sailfishos.org/package/view_file/sailfishos:chum:testing/harbour-osmscout/_service?expand=1

You have been added as a maintainer of sailfishos:chum:testing/harbour-osmscout . So, for next updates, you make the changes in :testing and then submit them to sailfishos:chum from sailfishos:chum. 

As you can see, version is now a bit complicated as that last commit is not tagged. In future, with the next update, when you use tagged commit the versioning will work as expected.

Closing over here.

**Comment by Karry** [comment]
Thank you. I will try the update process with next release. It would be great that whole release process (to Github, Harbour, OpenRepos, Chum) would be scriptable :-) I am publishing new release ~monthly period, so it is not big pain, but it includes many manual steps. Do you plan to prepare some command line utility for developers using Chum? I expect that OBS has some REST api. Or not?

**Comment by rinigus** [comment]
You can use `osc` for scripting. For example, get the current source (_service)

```
osc co sailfishos:chum:testing/harbour-osmscout
```

and then go to `sailfishos:chum:testing/harbour-osmscout` directory and change `revision` tag. After that it is just a matter of update via `osc` and submitting "submit request" (again via osc) to "sailfishos:chum". This all should be scriptable.
