### ISSUE TITLE
Feature request: Reroute

### ISSUE THREAD

**Issue by carlosgonz0** [Karry/osmscout-sailfish#293]

**Comment by Karry** [comment]
Hi. What exactly do you mean with "reroute" ? :-) When you leave planned track, router is trying to find a new one...

**Comment by carlosgonz0** [comment]
Yes rerouting if i deviate of the track, i going to do new test. I liked yesterday how OSMScout  work on Navigation on Sailfish 4.4 GNSS improvement by Michal. Thank you Karry.

**Comment by Karry** [comment]
Is the issue still exists? Feel free to reopen with more details.
