### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#295]
Hi 

You have add a lot of strings with underscores for example "amenity_cafe". 
Should I translate them with underscores?

**Comment by Karry** [comment]
Hi. 

There is the new feature of "active icons", that easily shows the object type, name (or operator, ref..) and possibly other details (website, phone).

![obrazek](https://user-images.githubusercontent.com/309458/162953277-601e26d5-640d-4cd9-a25d-3fd1c9fe4e6b.png)


In this place is used internal osmscout database type as translation string. So the `amenity_cafe` means OSM objects with [amenity=cafe tag](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe). Use some short name / phrase without underscore please. When you are using English as translation source, there are "translated" strings already: https://github.com/Karry/osmscout-sailfish/blob/master/translations/en.ts#L1817

**Comment by atlochowski** [comment]
thanks for explanation
