### ISSUE TITLE
Default dir on first start is ~/Osm not ~/Documents/Osm

### ISSUE THREAD

**Issue by thigg** [Karry/osmscout-sailfish#299]
1. Start app for the first time
2. On Welcome screen click the button to select the default storage folder

IS: ~/Osm is configured

SHOULD: ~/Documents/Osm

**Comment by Karry** [comment]
Hi, what do you mean with welcome screen? Are you sure that you are talking about "OSM Scout" and not ["OSM Scout server"](https://github.com/rinigus/osmscout-server/) from @rinigus ?

**Comment by Karry** [comment]
Issue is for osm scout server I believe...
