### ISSUE TITLE
The app only shows a white screen and nothing else.

### ISSUE THREAD

**Issue by cIddegh** [Karry/osmscout-sailfish#304]
When I start OSM Scout, I only get a white screen and nothing else. The app used to work just fine until version 2.21-1, but 2.23-1 and 2.24-1 both show this behavior.
I am on a Jolla 1 device with Sailfish 3.4.0.24 (the latest one available as of today).

Any ideas, what could be going wrong and how to solve it?

**Comment by Karry** [comment]
Hi. Recent versions are using new sharing api, that is not supported on Jolla 1. Because of that, you should use build from jolla1 branch, available on OpenRepos here: https://openrepos.net/content/karry/osm-scout-jolla-1

**Comment by cIddegh** [comment]
Hi. Thank you for the info. I am sorry to hear, that my good old Jolla 1 seems to start to drop out of the mainstream support. I currently have downgraded back to the last working version, but I will try the jolla1 branch.
Does it mean, that I should not try to update the app via the jolla-store anymore, because that would get me back to the unsupported main branch? Or can I still update via the store once I am on the jolla1 branch version?

**Comment by cIddegh** [comment]
Switched to branch now. Works! Thanks!

**Comment by Karry** [comment]
Great to hear that. "jolla1" variant is available just via open-repos. I just drop sharing support there, because sharing is using the new api...
