### ISSUE TITLE
UI improvement: Indicate that menu is scrollable

### ISSUE THREAD

**Issue by dyraig** [Karry/osmscout-sailfish#314]
I just spent a significant amount of time figuring out how to change OSM Scout from imperial to metric system. For the life of me, I could not find the settings page - I could open the menu with the hamburger button, but did not see any "Settings"-category - see screenshot:
![Screenshot_20221229_001](https://user-images.githubusercontent.com/19952060/209946179-4a55553f-db6b-4400-b91b-cceae815427c.png)

It was only after accidentally turning the phone to landscape that I noticed that there are more menu points further down ("Settings" was the next one down the list and became just visible in landscape). Maybe it is possible to have a scrollbar visible in the menu to make it clear that the menu is in fact scrollable? This happened to me on an Xperia XA2, but I remember having the same issue on the Xperia X as well (same screen resolution?).

**Comment by Karry** [comment]
Good point. I will add touch hint, that will be shown when you open menu first time and second time... These touch hints are good practice in Sailfish.

![obrazek](https://user-images.githubusercontent.com/309458/210455454-57d957ac-f59d-4082-a506-baa542989776.png)

**Comment by dyraig** [comment]
Ah - yes, that's a nice option, too! Nice!
