### ISSUE TITLE
Map for City of Berne crashes app

### ISSUE THREAD

**Issue by ToFuCH** [Karry/osmscout-sailfish#325]
When searching for an address within the city of Berne, Switzerland the app crashes consistently. Also when zooming in manually on Berne the app crashes on level 13 as well. This problem persists already since before the last update of the app and during two updates of the offline maps of Switzerland. When turning on online maps (while still having the offline version loaded) the problem still persists.

**Comment by Karry** [comment]
Hi. Thank you for report. I was able to reproduce it even on desktop build of libosmscout. I will work on the fix asap.

**Comment by Karry** [comment]
This bug is obvious, here is the fix: https://github.com/Framstag/libosmscout/pull/1517 It will be included in next release.

**Comment by ToFuCH** [comment]
Thanks for your quick as always responses, but would you please publish this bugfix as soon as possible.
I assume it has hit me again and this time renders OSMScout unusable. I am traveling in the area of Lemmer in the Netherlands and when zooming and panning the map around this town, the app frequently crashed. Then I had a route calculated there and when I wanted to switch into navigation mode, i.e. display the map, the app crashed. Since then I cannot use it anymore because whenever it starts up, it immediately crashes. I assume because it wants to display that most recent map again.
Is there a possibility to get this remedied otherwise, e.g.  by deleting a file where this information is stored or by starting from terminal with a switch?

**Comment by Karry** [comment]
Hi. Updated app was released on OpenRepos and Chum already. New version is waiting for QA review in Jolla Harbour eight days already. So you may install new version from OpenRepos or Chum or wait few days...

**Comment by Karry** [comment]
New version was released on Github and OpenRepos. It seems that Harbour store suspend to accept new updates :-/
