### ISSUE TITLE
Impossible to fork original libosmscout

### ISSUE THREAD

**Issue by phhorrein** [Karry/osmscout-sailfish#36]
As osmscout-sailfish is a fork of the original libosmscout repository, it is not possible (or at least not straightforward) to also contribute to libosmscout upstream. Since osmscout-sailfish does not use the code anymore, but downloads it as dependency instead, maybe it would be possible to "unfork" the repo ?

Pierre-Henri

**Comment by Karry** [comment]
Hi. It makes sense. I will create request to github support - it seems that it is the only way how to do it without lost of issues, watchers...

**Comment by Karry** [comment]
It was fast. It seems to be detached properly.

**Comment by phhorrein** [comment]
Great! It works. Thanks a lot.

**Comment by phhorrein** [comment]
Do you plan on merging the changes in your fork of libosmscout in the original repo ? I'm making some modifications in the Qt interface (I will probably make a pull request), and I was wondering which repo I should use as a basis.

**Comment by Karry** [comment]
Prepare your changes and merge requests for [upstream library](https://github.com/Framstag/libosmscout) please :-) OSM Scout for Sailfish should be compatible with it.

My fork (that I am using for builds) contains just a few extra patches (but some of them may seems to be huge):
 - patches for backward compatibility with older database formats
 - different internal representation of node sequences (ways and areas) - it improves memory footprint, but it is slower on cheap systems like Raspberry Pi 

These patches may be useful, but adds too much complexity and may be problematic on different platforms. So we decided to keep them out of upstream library...

**Comment by Karry** [comment]
Btw, when you plan to contribute to libosmscout, you may want to subscribe this mailing list: https://sourceforge.net/p/libosmscout/mailman/?source=navbar

Merge requests or issues are discussed on Github, but some general discussions are just on this list...
