### ISSUE TITLE
GPX tracks

### ISSUE THREAD

**Issue by accountgit** [Karry/osmscout-sailfish#37]
Will be very interesting if were possible to see GPX tracks over the map.

**Comment by Karry** [comment]
Hi. GPX recording and viewing is in my TODO list. But is too bottom on the list of features that I am planning... I am open to merge requests of course :-)

**Comment by Karry** [comment]
Hi. New release 1.0 supports "collections" - internal database of waypoints and tracks. 

 - You can import GPX file or export to it. 
 - It is possible to display some collection on the main and cover page. 
 - And you can create new waypoint directly from the application (just click to the star button on the place detail page).
