### ISSUE TITLE
search does not work (without offline map)

### ISSUE THREAD

**Issue by PawelSpoon** [Karry/osmscout-sailfish#45]
i think to remember an issue with search, but could not find it. so i am opening a new one.
tried to search for city: Salzburg, Graz, no results. salzburg deto, street in Salzburg also nothing. should this work already ? i have no downloaded maps yet. austria might be 20percent downloaded

**Comment by Karry** [comment]
Search works only with offline maps, there is no support for online search providers yet... It would be great to extend library to make search extendable.

**Comment by Karry** [comment]
I just added warning when there is no offline database yet. It is displayed instead of search or navigation. I don't plan to add support for any online service now, there is Pure Maps that serves that job properly.
