### ISSUE TITLE
Update imported maps ?

### ISSUE THREAD

**Issue by physkets** [Karry/osmscout-sailfish#5]
Is imported map data updated when connected to the internet?

I had made some changes in the OSM database yesterday, but they do not seem to be displayed on my map even when I'm connected to the internet (I have this particular area imported for off-line use).

**Comment by Karry** [comment]
No. Offline database don't support incremental updates. Index computing, that is part of import process, is complex and memory expensive operation. It can't be done on mobile phone. Updates should make whole process even more complicated. 

You have to import whole area again from updated OSM export. If you update source code repository and compile import tool again, you will benefit from recent import fixes and updated import types...

**Comment by physkets** [comment]
Ah, I see...  Thanks!
