### ISSUE TITLE
Custom directory for offline maps (or ones compatible with OSM Scout Server)

### ISSUE THREAD

**Issue by Olf0** [Karry/osmscout-sailfish#51]
Oh, seems that one cannot reopen an issue, when not being the owner, or the one, who originally opened the issue.  So in continuation of issue #14: 

With the update from OSM Scout Server 0.6.2 to 0.7.0 (and newer), it became impossible to share the offline maps with OSM Scout (0.19 used; both installed from the Jolla Store) via their GUI-based settings.  Both have fixed, incompatible directory names now, i.e. \<chosen-OSMScoutServer-dirname\>/osmscout for OSM Scout Server (0.7.0 and higher) and either \~/Documents/Maps or \<SDcard\>/Maps for OSM Scout. 
Hence please implement a setting in OSM Scout to freely choose a directory for the offline maps *or* make the two preselected directories compatible with OSM Scout Server's map-directory scheme, e.g. make it a "~/OSMscout/osmscout *and* \<SDcard\>/OSMscout/osmscout"-pulley.  IMO \~/Documents is not the right place for putting huge offline maps files anyway, instead a separate directory in \~ fits better.

**Comment by Karry** [comment]
Hi. I want to keep application simple as possible. For that reason, I used combo box just with two options for selecting map destination: sdcard/Maps; Documents/Maps. Advanced users can always create symlinks and move maps to another locations...

To compatibility with server: I understand why @rinigus is using different map folder - his application uses different download server. Beyond "standard osmscout maps", server may download database for geocoder... And we have to change database format time-by-time. In such conditions, it is hard to keep everything in line and working. Again, if you or someone else want to share maps between OSMScout and OSMScout server, I suggest to use symlinks... It should works most the time, but keep in mind that some things may be broken then, like #52...

**Comment by Olf0** [comment]
@Karry: I do well understand your striving for simplicity.  So keeping a pulley with two options is absolutely reasonable, IMO. 
But as OSMscout and OSmscout Server are the primary users of libosmscout, I do believe it makes sense to be able to choose compatible directories from the GUI, at least in the long run (during the current, rapid development of and around libosmscout, separate directories are definitely useful).  Otherwise users of both programs have to keep Gigabytes of (more or less) duplicate map files around.
Hence (and for keeping those huge files out of \~/Documents) my suggestion for the directories \~/OSMscout/osmscout and \<SDcard\>/OSMscout/osmscout in the pulley, which are compatible with OSMscout Server.  One has to actively choose "OSMscout" as the prefixing directory in OSMscout Server, anyway, as the default is "Maps", IIRC.

**Comment by rinigus** [comment]
Indeed, in the server, you could use a different geocoder and, starting from 0.9.0, different backend for rendering - Mapnik. To make it possible to support multiple backends, I had to use different folder structure. Its also imposed by the different implementation of the map manager (part responsible for maps subscription/updates/removal) and the wish to be able to distribute maps via CDN on my side. 

In long run, I think we will converge in formats and it would be simple to use any of them. However, as mentioned in  https://github.com/Karry/osmscout-sailfish/issues/52 , be careful. And this incompatibility will be still there for few weeks until I get new libosmscout maps and the server out. 

Your suggestion with the default directories for OSM Scout would work (Maps.OSM is the default for the server), but does look rather odd from OSM Scout application point of view (i.e. it has to adapt to the scheme selected by others).

**Comment by Olf0** [comment]
This is the only reasonable solution, I can think of, with the following constraints given: 

- OSMscout should keep a two entry pulley, one entry with a directory under /home/nemo, the other with one on SDcard.
- The two directories shall have the same, easily recogniseable (as used by OSMscout / libosmscout) name. 
- An average user shall not be forced to use the command line for a solution. 
- OSMscout Server needs two directory levels to keep its maps etc. organised, and chose to name the map sub-directory "osmscout", while the upper directory is a arbitrary file path.
- The default directory name(s) should differ from the default prefixing directory name of OSMscout Server (Maps.OSM).
- The default maps directory for OSMscout shall bena separate directory (outside of \~/Documents).

**Comment by rinigus** [comment]
@Olf0, let's see what @Karry thinks about it. I will most probably update  libosmscout component before the next rollout of the maps (next after the update coming in few days), but there is always  a risk of incompatibilities.

**Comment by Karry** [comment]
Sorry Olf0, I am clossing this issue. I understand that it is impractical to download multiple map datasets and waste storage space, but keep everything in sync is time expensive and my priorities for this app are different.

Power users may use symlinks anyway.

Btw, Navit was released for SFOS, huray! It is using its own map format ;-)
