### ISSUE TITLE
Automatic map orientation

### ISSUE THREAD

**Issue by ktrace** [Karry/osmscout-sailfish#58]
Need automatic map orientation by  cardinal directions (NSEW).

**Comment by carlosgonzz** [comment]
yeap this  feature Is a  lot needed. @Karry  doing nice work on osmscout. thanks.

**Comment by Karry** [comment]
Hi. Automatic map orientation was introduced while navigation is on. Do you think that it is enough? I don't have compass in my device (Jolla C), so it is hard to test for me. And I prefer to have north on the top (when I am not in the car). So this issue has just minor priority for me...

**Comment by atlochowski** [comment]
For me it's enough.
