### ISSUE TITLE
Possibility to add some sentences to translate

### ISSUE THREAD

**Issue by Caballlero** [Karry/osmscout-sailfish#63]
- Sentence: Route! showed in the picture
![captura_20170726_001](https://user-images.githubusercontent.com/24536606/28651933-c7374cca-7252-11e7-8d18-b4d97bb77480.png)
- Sentence: All showed in the pictute
![captura_20170726_002](https://user-images.githubusercontent.com/24536606/28651941-ccb03e50-7252-11e7-92f7-61e6b2346e58.png)

Karry can you change "Routing"to "Calculating the route".THIS SENTENCES IS ONLY SHOWED WHEN I TRY GET A LONG ROUTE , then show this sentence. Note than the sentence routing exist in two time ,but i think this "Routing" sentence it is better to change to "Calculating the route"     = )

**Comment by Caballlero** [comment]
hello: karry
Any news of this?

**Comment by Karry** [comment]
Hi Carlos. Sorry, there is no change related with this issue. I was focussing to search recent months. Description of route steps is fully generated in C++ code now (see [`Router::GenerateRouteSteps`](https://github.com/Framstag/libosmscout/blob/master/libosmscout-client-qt/src/osmscout/Router.cpp#L529)) It is necessary to translate description there, or better, transfer all informations to QML and build translatable description in QML code.

**Comment by Caballlero** [comment]
0kay - How much of  work is to convert all the c ++ code to qml?

**Comment by Karry** [comment]
Well, pass all properties needed for building route commands to QML would be easy. But I want to bring real time navigation soon and it is possible that whole router will be reworked - I dont want to do it until navigation will be ready...

**Comment by Karry** [comment]
Latest version supports phrase translations from C++ code. I am closing it

**Comment by Caballlero** [comment]
Thanks
