### ISSUE TITLE
Do not delete old maps after downloading new ones

### ISSUE THREAD

**Issue by atlochowski** [Karry/osmscout-sailfish#73]
When I download for example new version of map of Poland I will have two versions in Document directory. Which is not good. After couple map updates memory of the phone will finish.
I think you should consider deleting old version of maps when downloading of new ones is finished.

**Comment by Karry** [comment]
Hi. Absolutely agree. There is need to support database updates... 

But as usual, my resources are limited. I can't promise when it will be implemented :-(

**Comment by Karry** [comment]
Hi.

I am closing this issue. Newly released version (0.29) supports upgrading of databases. I will works just with newly downloaded maps. Map manager needs some metadata stored in map directory...
