### ISSUE TITLE
Slovenia doesn't have a border

### ISSUE THREAD

**Issue by TzwennD** [Karry/osmscout-sailfish#82]
It seems this boarder is missing ;-)

Of course, this is a minor problem..

**Comment by Karry** [comment]
Hi. Country borders are commented out in map style now. It is for performance reason, because some long border lines may really slow down rendering. I am looking for the way how to bring it back with less performance penalty...

**Comment by Karry** [comment]
I will reopen it, it is valid issue that should be solved (performance problem with large objects).

**Comment by Karry** [comment]
Rendering performance of huge areas was improved by this merge request: https://github.com/Framstag/libosmscout/pull/669 , so I return country boundaries to the stylesheets in version 1.2... I am closing this issue ;-)
