### ISSUE TITLE
Disable double tap

### ISSUE THREAD

**Issue by TzwennD** [Karry/osmscout-sailfish#83]
Double tap centers on current position.

Can you please disable it or allow disabling it from the preferences? It is really annoying when "looking something up". Especially when this something is far away from the current location.

Thanks a lot for the great app!

**Comment by Karry** [comment]
Hi. What element and what on what page you are tapping? When you double tab on map (on default page), it should just zoom in. But when you double tap to "current location button" (button in right bottom corner), it move view to current location and lock it...

**Comment by TzwennD** [comment]
Sorry, I am stupid..

I mixed up the apps :-(

Sorry about that!

**Comment by Karry** [comment]
No problem :-)
