### ISSUE TITLE
osmscount v28 crashing

### ISSUE THREAD

**Issue by Caballlero** [Karry/osmscout-sailfish#94]
To reproduce: 
go to Setting > modify , Map-magnification

**Comment by Karry** [comment]
Ups. I cant reproduce it, even with fresh 0.28 installation. I will send you new package for few tests at evening, I will need coredump from this crash (I dont have debug symbols from 0.28 binary anymore).

**Comment by Karry** [comment]
Hi. Can you please install this build: https://osmscout.karry.cz/tests/harbour-osmscout-0.29-1.armv7hl.rpm on your device, enable core dumps, reproduce crash and send me the coredump?

...just open terminal on your phone and type these two commands:
```
ulimit -c unlimited
harbour-osmscout
```
after crash, there should be some file in your home directory (`/home/nemo`) with name `core.####` (suffix is PID of process). Please upload it somewhere and send me link to email lukas.karas@centrum.cz (it willl contains complete memory of osmscout process, it will contain your gps location).

**Comment by atlochowski** [comment]
I will send you logs a well.
But here you have message error "*** Error in `harbour-osmscout': malloc(): memory corruption (fast): 0x0032a480 ***
Przerwane (core dumped)"

**Comment by Karry** [comment]
Thank you @atlochowski . It will be useful hopefully. I got valid stacktrace, it is clear that invalid allocation was from renderer thread, stack trace contains this sequence:
```
...
osmscout::MapPainterQt::GetTextDimension
osmscout::MapPainter::RegisterPointWayLabel
osmscout::MapPainter::CalculateWayShieldLabels
osmscout::MapPainter::PrepareWays
osmscout::MapPainter::PreprocessData
osmscout::MapPainter::Draw
...
```
I will investigate it more deeply at night...

**Comment by Karry** [comment]
Previous stack trace ^^^ was invalid - I was using invalid debug symbols for some libraries probably... Now, it seems to be clear that problem is my old memory optimisation that was not designed as multithreaded. But after recent changes in core library may be map primitives accessed from  multiple threads synchronised by read-write locks...

Fix is simple, I will just use different branch of libosmscout library... I will send you new build for testing morning.

**Comment by Karry** [comment]
It is here: https://osmscout.karry.cz/tests/test2/harbour-osmscout-0.29-1.armv7hl.rpm
Can you please test it?

**Comment by atlochowski** [comment]
it looks that problem is solved

**Comment by Karry** [comment]
Thank you. I will test it (memory consumption mainly) and will release new version then...

**Comment by Caballlero** [comment]
Thanks guys...
