### ISSUE TITLE
osmscount- sailfish; New Icons  

### ISSUE THREAD

**Issue by ghost** [Karry/osmscout-sailfish#99]
HI  @Karry 
I would like see this app with a nice icons ,high DPI,Highlighted colors,High Precision Edges. So I want to talk to Alain-Molteni to create it ,he is the best on sailfish icons **= )**  

- I believe in osmScount that It deserve a nice Icon...    
- I will pay the cost for the Icon
- So I open this ticket to discuss **Metaphors**?  for it

**Comment by Karry** [comment]
Hi.

Majority of icons is based on vector images, there is no problem to use vector icons directly to get best result on HiDPI screen.

Question is, what icons do you want to replace? There is various sets of icons:
 - main application icon, created by me, used in launcher. It may be replaced with some nicer :-)
 - menu icons, for these icons are used system icons from Sailfish. I dont want to change it
 - icons for map types (poi), used in search page, reverse lookup page... They are based on free Mapbox icons (if I remember). I like these icons, these are similar to system icons. But dont cover all types...
 - poi icons used in map renderer. These are copied from upstream libosmscout repository. We may replace it. These icons are hard to distinguish, dont cover all types...

**Comment by Karry** [comment]
I forgot to icons for routing steps, these are copied from poor map. I dont remember who was original author... We may replace it. But navigation needs to be rewritten, current icon set may change...

**Comment by Caballlero** [comment]
Just the main icon,created for you. the rest is OK by now.

**Comment by Karry** [comment]
Why not :-) I just want that new icon will be provided with some free license (cc-by-sa for example) and meet Sailfish icon visual style.

**Comment by Caballlero** [comment]
Yes  will much better, So poor-map-navigator icons is not free license? Or you want own icons?

**Comment by Karry** [comment]
Navigation icons are originaly from Mapbox ( https://github.com/otsaloma/poor-maps/tree/master/qml/icons/navigation ). These are usable without any restriction. I am ok with it. I just plan to add support for highway lanes and evaluate route steps better. It is possible that I will need to create new icons then. But it is hard to estimate when (and if) it will be ;-)

**Comment by Caballlero** [comment]
karry, what icon framer do you wish_?

![sailfishframer](https://user-images.githubusercontent.com/24536606/37856265-fb95bd6a-2ec9-11e8-906c-312bbf90f5fd.jpg)

**Comment by Karry** [comment]
Hi. I have no preference of specific shape. It depends on what will be on the icon ;-) When there will be globe, it is nonsense use square icon...

**Comment by Caballlero** [comment]
Yes the globe Icon is the best option to simulate a P.O.I
What colors do you thing work on It?

**Comment by Karry** [comment]
Great! Sorry that I don't reply to your question about color, I just have no preference about it :-)

**Comment by ferlanero** [comment]
Hi! I'll start working on a new icon for OSMScout in a few days. It's ok for you?

**Comment by atlochowski** [comment]
To be honest current app icon is really nice. It's simple and have everythink what is needed to now it's maps, navigation app.

**Comment by ferlanero** [comment]
Yes, I have been working on it  but unfortunately last week I have suffered  a traffic accident. I have been in the hospital and I have to stop working on icon. Once I have recovered my normal life I'll continue working on it :)

**Comment by Karry** [comment]
I wish you early recovery!

**Comment by carlosgonzz** [comment]
@ferlanero where you are :  )

**Comment by GNUuser** [comment]
Hello @Karry 
I just want to know why this PR look like open when was closed?

**Comment by Karry** [comment]
Issue #155 is closed, but this one #99 is still open...

**Comment by GNUuser** [comment]
Please shut down this old PR. It already fixed time ago.

**Comment by Karry** [comment]
Agree, lets close it. I am still open to UI improvements or just icon changes. Just open merge request when you want to contribute.
